# Generated by Django 4.1 on 2023-07-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='space_agency.slider'),
        ),
    ]
