# Generated by Django 4.1 on 2023-07-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_agency', '0002_slider_image_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='image',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
