# Generated by Django 4.1 on 2023-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_agency', '0003_alter_image_options_image_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='slider',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
